import type { Scenario } from './types';

/**
 * Showcase Demo v2.4 - International Crisis Simulation
 *
 * Flow (~5 minutes):
 * 1. Intro - 12 aircraft with international carriers
 * 2. Air India Hijack - Norwegian hijacker (Wakanda), Captain Sharma & FA Priya
 * 3. Hero Mode - Qantas A380, Sarah fights off Swedish hijacker
 * 4. Stealth Incursion (Russian SU-57)
 * 5. TCAS Near Mid-Air Collision
 * 6. Severe Weather - Tornado
 * 7. Finale
 *
 * Google Cloud TTS with Chirp voices for multi-accent experience
 */
export const showcaseDemoScenario: Scenario = {
  id: 'showcase-demo',
  title: 'Crisis Showcase',
  description: 'International crisis: Air India hijack, Qantas hero rescue, stealth, TCAS',
  icon: 'flame',
  duration: 5,
  initialState: {
    tracks: [
      // Air India - will be hijacked
      {
        trackId: 'TRK-SD-001',
        callsign: 'AIC302',
        latitudeDeg: 42.3,
        longitudeDeg: -71.0,
        altitudeFt: 39000,
        headingDeg: 270,
        speedKt: 510,
        verticalRateFpm: 0,
        confidence: 0.98,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'AIC',
        aircraftType: 'B777',
        countryCode: 'IN',
        souls: 350,
      },
      // Qantas - Hero Mode flight
      {
        trackId: 'TRK-SD-002',
        callsign: 'QFA8',
        latitudeDeg: 42.45,
        longitudeDeg: -71.6,
        altitudeFt: 40000,
        headingDeg: 90,
        speedKt: 520,
        verticalRateFpm: 0,
        confidence: 0.97,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'QFA',
        aircraftType: 'A380',
        countryCode: 'AU',
        souls: 489,
      },
      // British Airways
      {
        trackId: 'TRK-SD-003',
        callsign: 'BAW117',
        latitudeDeg: 42.6,
        longitudeDeg: -70.5,
        altitudeFt: 37000,
        headingDeg: 250,
        speedKt: 490,
        verticalRateFpm: 0,
        confidence: 0.97,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'BAW',
        aircraftType: 'A350',
        countryCode: 'GB',
        souls: 325,
      },
      // US Carriers
      {
        trackId: 'TRK-SD-004',
        callsign: 'DAL1892',
        latitudeDeg: 42.35,
        longitudeDeg: -70.8,
        altitudeFt: 35500,
        headingDeg: 270,
        speedKt: 460,
        verticalRateFpm: 0,
        confidence: 0.96,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'DAL',
        aircraftType: 'A330',
        countryCode: 'US',
        souls: 287,
      },
      {
        trackId: 'TRK-SD-005',
        callsign: 'AAL445',
        latitudeDeg: 42.1,
        longitudeDeg: -71.3,
        altitudeFt: 28000,
        headingDeg: 180,
        speedKt: 380,
        verticalRateFpm: -1500,
        confidence: 0.98,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'AAL',
        aircraftType: 'B738',
        countryCode: 'US',
        souls: 156,
      },
      {
        trackId: 'TRK-SD-006',
        callsign: 'UAL2547',
        latitudeDeg: 42.55,
        longitudeDeg: -71.15,
        altitudeFt: 31000,
        headingDeg: 135,
        speedKt: 420,
        verticalRateFpm: 0,
        confidence: 0.94,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'UAL',
        aircraftType: 'B789',
        countryCode: 'US',
        souls: 274,
      },
      {
        trackId: 'TRK-SD-007',
        callsign: 'SWA3021',
        latitudeDeg: 41.85,
        longitudeDeg: -71.1,
        altitudeFt: 24000,
        headingDeg: 45,
        speedKt: 410,
        verticalRateFpm: 1500,
        confidence: 0.95,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'SWA',
        aircraftType: 'B737',
        countryCode: 'US',
        souls: 143,
      },
      {
        trackId: 'TRK-SD-008',
        callsign: 'FDX892',
        latitudeDeg: 41.7,
        longitudeDeg: -71.7,
        altitudeFt: 38000,
        headingDeg: 0,
        speedKt: 480,
        verticalRateFpm: 0,
        confidence: 0.93,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'FDX',
        aircraftType: 'B77W',
        countryCode: 'US',
        souls: 2,
      },
      {
        trackId: 'TRK-SD-009',
        callsign: 'JBU1157',
        latitudeDeg: 42.2,
        longitudeDeg: -70.9,
        altitudeFt: 29000,
        headingDeg: 225,
        speedKt: 400,
        verticalRateFpm: 0,
        confidence: 0.95,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'JBU',
        aircraftType: 'A321',
        countryCode: 'US',
        souls: 185,
      },
      {
        trackId: 'TRK-SD-010',
        callsign: 'ASA1205',
        latitudeDeg: 41.95,
        longitudeDeg: -71.85,
        altitudeFt: 30000,
        headingDeg: 90,
        speedKt: 430,
        verticalRateFpm: 0,
        confidence: 0.96,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'ASA',
        aircraftType: 'B739',
        countryCode: 'US',
        souls: 178,
      },
      // Other International
      {
        trackId: 'TRK-SD-011',
        callsign: 'AFR023',
        latitudeDeg: 42.0,
        longitudeDeg: -71.5,
        altitudeFt: 36000,
        headingDeg: 60,
        speedKt: 470,
        verticalRateFpm: 0,
        confidence: 0.96,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'AFR',
        aircraftType: 'A330',
        countryCode: 'FR',
        souls: 277,
      },
      {
        trackId: 'TRK-SD-012',
        callsign: 'UAE231',
        latitudeDeg: 41.8,
        longitudeDeg: -71.4,
        altitudeFt: 41000,
        headingDeg: 45,
        speedKt: 495,
        verticalRateFpm: 0,
        confidence: 0.97,
        sequence: 1,
        updatedAt: new Date().toISOString(),
        airline: 'UAE',
        aircraftType: 'A380',
        countryCode: 'AE',
        souls: 489,
      },
    ],
    alerts: [],
    predictions: [],
  },
  steps: [
    // ==================== INTRO ====================
    {
      id: 'intro-1',
      narrative: 'ATCS Next Gen online. Boston Sector 33. 12 aircraft under control. Heavy international traffic today.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 6000,
    },
    {
      id: 'intro-2',
      narrative: 'All sensors nominal. AI threat detection active. Air India 302 and Qantas 8 inbound from overseas.',
      spotlight: { type: 'component', id: 'predictions' },
      autoAdvance: 6000,
    },

    // ==================== AIR INDIA HIJACK (Norwegian hijacker from Wakanda) ====================
    {
      id: 'hijack-begin',
      narrative: 'MAYDAY received from Air India 302. Emergency transponder active. Squawk 7500 confirmed.',
      spotlight: { type: 'flight', callsign: 'AIC302' },
      autoAdvance: 8000,
      events: [
        {
          delay: 0,
          type: 'updateTrack',
          payload: { trackId: 'TRK-SD-001', squawkCode: '7500', visualState: 'hijacked' },
        },
        {
          delay: 500,
          type: 'addAlert',
          payload: {
            alertId: 'ALT-HIJACK-01',
            severity: 'CRITICAL',
            alertType: 'EMERGENCY_DECLARED',
            message: 'HIJACKING: AIC302 Boeing 777. 350 souls. Armed suspect in cockpit.',
            involvedFlightIds: ['AIC302'],
            sectorId: 'BOS_33',
            timestamp: new Date().toISOString(),
            acknowledged: false,
          },
        },
      ],
    },
    {
      id: 'hijack-captain',
      narrative: 'Captain Sharma: Boston, this is Air India 302 heavy. A man with a weapon has entered my cockpit. He is speaking Norwegian. He claims to be from Wakanda. Please advise.',
      atcCommand: 'Air India 302, Boston Center copies. Keep transmitting. Help is coming.',
      spotlight: { type: 'flight', callsign: 'AIC302' },
      autoAdvance: 10000,
    },
    {
      id: 'hijack-demands',
      narrative: 'Norwegian hijacker speaking: Jeg krever at dette flyet lander i Wakanda umiddelbart! No movement! I have control of this plane now.',
      spotlight: { type: 'flight', callsign: 'AIC302' },
      autoAdvance: 10000,
      events: [
        {
          delay: 0,
          type: 'updateTrack',
          payload: { trackId: 'TRK-SD-001', headingDeg: 180, dataCorruption: 0.2 },
        },
      ],
    },
    {
      id: 'hijack-fa',
      narrative: 'Flight Attendant Priya: Passengers are panicking. He has locked the cockpit door. Captain Sharma is trying to negotiate. We are descending rapidly.',
      spotlight: { type: 'flight', callsign: 'AIC302' },
      autoAdvance: 10000,
      events: [
        {
          delay: 500,
          type: 'addAlert',
          payload: {
            alertId: 'ALT-HIJACK-02',
            severity: 'CRITICAL',
            alertType: 'LOSS_OF_SEPARATION',
            message: 'AIR INDIA 302: Hijacker making demands. Course deviation detected.',
            involvedFlightIds: ['AIC302'],
            sectorId: 'BOS_33',
            timestamp: new Date().toISOString(),
            acknowledged: false,
          },
        },
      ],
    },
    {
      id: 'hijack-descent',
      narrative: 'Air India 302 in uncontrolled descent. Hijacker has seized the controls. NORAD scrambling F-22 Raptors from Langley.',
      spotlight: { type: 'flight', callsign: 'AIC302' },
      autoAdvance: 8000,
      events: [
        {
          delay: 0,
          type: 'updateTrack',
          payload: {
            trackId: 'TRK-SD-001',
            verticalRateFpm: -6000,
            altitudeFt: 20000,
            speedKt: 400,
            dataCorruption: 0.5,
          },
        },
      ],
    },
    {
      id: 'hijack-crash',
      narrative: 'Radar contact lost with Air India 302. 350 souls on board. Primary target fading. We could not save them.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 10000,
      events: [
        {
          delay: 0,
          type: 'updateTrack',
          payload: {
            trackId: 'TRK-SD-001',
            visualState: 'crashed',
            altitudeFt: 0,
            speedKt: 0,
            confidence: 0,
            transponderActive: false,
          },
        },
        { delay: 500, type: 'removeAlert', payload: { id: 'ALT-HIJACK-01' } },
        { delay: 600, type: 'removeAlert', payload: { id: 'ALT-HIJACK-02' } },
        {
          delay: 800,
          type: 'addAlert',
          payload: {
            alertId: 'ALT-CRASH',
            severity: 'CRITICAL',
            alertType: 'EMERGENCY_DECLARED',
            message: 'AIRCRAFT DOWN: AIC302. 350 fatalities. Search and rescue dispatched.',
            involvedFlightIds: ['AIC302'],
            sectorId: 'BOS_33',
            timestamp: new Date().toISOString(),
            acknowledged: false,
          },
        },
      ],
    },
    {
      id: 'crash-aftermath',
      narrative: 'Some battles cannot be won. We mark their position. Search and rescue en route. But wait. Another crisis is developing. Qantas 8 is declaring emergency.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 10000,
      events: [
        { delay: 1000, type: 'removeAlert', payload: { id: 'ALT-CRASH' } },
      ],
    },

    // ==================== HERO MODE: QANTAS A380 RESCUE ====================
    {
      id: 'hero-trigger',
      narrative: 'Sarah: Mayday mayday! This is Qantas 8. There was a hijacker speaking Swedish! I knocked him out but... both pilots are unconscious. Oh god, I have 489 people on this plane. Please help us!',
      spotlight: { type: 'flight', callsign: 'QFA8' },
      autoAdvance: 12000,
      events: [
        {
          delay: 0,
          type: 'updateTrack',
          payload: {
            trackId: 'TRK-SD-002',
            visualState: 'hero',
            squawkCode: '7700',
          },
        },
        {
          delay: 500,
          type: 'addAlert',
          payload: {
            alertId: 'ALT-HERO',
            severity: 'CRITICAL',
            alertType: 'EMERGENCY_DECLARED',
            message: 'HERO MODE: QFA8 Airbus A380. 489 souls. Guide Sarah to land at JFK.',
            involvedFlightIds: ['QFA8'],
            sectorId: 'BOS_33',
            timestamp: new Date().toISOString(),
            acknowledged: false,
          },
        },
        {
          delay: 1500,
          type: 'triggerHeroMode',
          payload: { active: true },
        },
      ],
    },
    {
      id: 'hero-active',
      narrative: 'Hero Mode engaged. Sarah has control of the A380 but has never flown before. The Swedish hijacker is unconscious. 489 souls depend on you.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 60000,
    },
    {
      id: 'hero-complete',
      narrative: 'Qantas 8 is on the ground at JFK. Sarah and 489 passengers are safe. Emergency services on scene. An Australian hero made aviation history.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 10000,
      events: [
        { delay: 0, type: 'triggerHeroMode', payload: { active: false } },
        { delay: 0, type: 'removeAlert', payload: { id: 'ALT-HERO' } },
        {
          delay: 0,
          type: 'updateTrack',
          payload: { trackId: 'TRK-SD-002', visualState: 'normal', squawkCode: '1200' },
        },
      ],
    },

    // ==================== RUSSIAN STEALTH ====================
    {
      id: 'stealth-detect',
      narrative: 'Anomaly detected. Intermittent radar return, no transponder. Bearing 045.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 6000,
      events: [
        {
          delay: 200,
          type: 'addAlert',
          payload: {
            alertId: 'ALT-STEALTH-01',
            severity: 'WARNING',
            alertType: 'DEVIATION_DETECTED',
            message: 'UNKNOWN CONTACT: Intermittent radar return. No transponder.',
            involvedFlightIds: ['UNKNOWN'],
            sectorId: 'BOS_33',
            timestamp: new Date().toISOString(),
            acknowledged: false,
          },
        },
      ],
    },
    {
      id: 'stealth-id',
      narrative: 'Contact confirmed. Speed Mach 1.8, altitude 45,000. Russian SU-57 Felon in US airspace.',
      atcCommand: 'All aircraft, unknown traffic bearing 045. Stand by for vectors.',
      spotlight: { type: 'component', id: 'alerts' },
      autoAdvance: 8000,
      events: [
        {
          delay: 0,
          type: 'addAlert',
          payload: {
            alertId: 'ALT-STEALTH-02',
            severity: 'CRITICAL',
            alertType: 'LOSS_OF_SEPARATION',
            message: 'HOSTILE: SU-57 Felon violating US airspace. NORAD notified.',
            involvedFlightIds: ['UNKNOWN'],
            sectorId: 'BOS_33',
            timestamp: new Date().toISOString(),
            acknowledged: false,
          },
        },
      ],
    },
    {
      id: 'stealth-response',
      narrative: 'F-22 Raptors scrambling from Langley. Civil traffic vectoring clear.',
      atcCommand: 'British Airways 117, turn left heading 180. Descend flight level 330.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 8000,
      events: [
        { delay: 0, type: 'updateTrack', payload: { trackId: 'TRK-SD-003', headingDeg: 180, verticalRateFpm: -1500 } },
        { delay: 300, type: 'updateTrack', payload: { trackId: 'TRK-SD-011', headingDeg: 180 } },
      ],
    },
    {
      id: 'stealth-resolved',
      narrative: 'Russian aircraft reversed course. Exiting US airspace. Crisis averted.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 6000,
      events: [
        { delay: 200, type: 'removeAlert', payload: { id: 'ALT-STEALTH-01' } },
        { delay: 400, type: 'removeAlert', payload: { id: 'ALT-STEALTH-02' } },
      ],
    },

    // ==================== TCAS ====================
    {
      id: 'tcas-alert',
      narrative: 'Traffic alert! Delta 1892 and American 445 converging fast. TCAS activating!',
      spotlight: { type: 'component', id: 'predictions' },
      autoAdvance: 6000,
      events: [
        {
          delay: 0,
          type: 'addPrediction',
          payload: {
            id: 'PRED-TCAS',
            predictionType: 'CONFLICT',
            involvedFlights: ['DAL1892', 'AAL445'],
            probability: 0.97,
            predictedTime: new Date(Date.now() + 30000).toISOString(),
            description: 'COLLISION COURSE: 443 souls at risk!',
          },
        },
        {
          delay: 200,
          type: 'addAlert',
          payload: {
            alertId: 'ALT-TCAS-01',
            severity: 'CRITICAL',
            alertType: 'CONFLICT_PREDICTED',
            message: 'TCAS RA: DAL1892 CLIMB. AAL445 DESCEND. Execute immediately!',
            involvedFlightIds: ['DAL1892', 'AAL445'],
            sectorId: 'BOS_33',
            timestamp: new Date().toISOString(),
            acknowledged: false,
          },
        },
      ],
    },
    {
      id: 'tcas-execute',
      narrative: 'TCAS resolution advisory executing. Both aircraft maneuvering.',
      atcCommand: 'Delta 1892, climb flight level 390. American 445, descend flight level 240.',
      spotlight: { type: 'flight', callsign: 'DAL1892' },
      autoAdvance: 8000,
      events: [
        { delay: 0, type: 'updateTrack', payload: { trackId: 'TRK-SD-004', verticalRateFpm: 4000, altitudeFt: 39000 } },
        { delay: 0, type: 'updateTrack', payload: { trackId: 'TRK-SD-005', verticalRateFpm: -4000, altitudeFt: 24000 } },
      ],
    },
    {
      id: 'tcas-clear',
      narrative: 'Conflict resolved. 15,000 feet separation achieved. 443 lives saved.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 6000,
      events: [
        { delay: 0, type: 'updateTrack', payload: { trackId: 'TRK-SD-004', verticalRateFpm: 0 } },
        { delay: 0, type: 'updateTrack', payload: { trackId: 'TRK-SD-005', verticalRateFpm: 0 } },
        { delay: 300, type: 'removePrediction', payload: { id: 'PRED-TCAS' } },
        { delay: 400, type: 'removeAlert', payload: { id: 'ALT-TCAS-01' } },
      ],
    },

    // ==================== TORNADO ====================
    {
      id: 'tornado-warn',
      narrative: 'Severe weather alert. EF-3 tornado, 25 miles southwest. Multiple aircraft in path.',
      spotlight: { type: 'component', id: 'alerts' },
      autoAdvance: 6000,
      events: [
        {
          delay: 0,
          type: 'addAlert',
          payload: {
            alertId: 'ALT-TORNADO',
            severity: 'CRITICAL',
            alertType: 'WEATHER_HAZARD',
            message: 'EF-3 TORNADO: FDX892, ASA1205, SWA3021 threatened. Rerouting!',
            involvedFlightIds: ['FDX892', 'ASA1205', 'SWA3021'],
            sectorId: 'BOS_33',
            timestamp: new Date().toISOString(),
            acknowledged: false,
          },
        },
      ],
    },
    {
      id: 'tornado-reroute',
      narrative: 'AI weather avoidance executing. Three aircraft deviating from tornado path.',
      atcCommand: 'FedEx 892, turn right heading 090. Climb flight level 400.',
      spotlight: { type: 'flight', callsign: 'FDX892' },
      autoAdvance: 8000,
      events: [
        { delay: 0, type: 'updateTrack', payload: { trackId: 'TRK-SD-008', headingDeg: 90, verticalRateFpm: 2000 } },
        { delay: 200, type: 'updateTrack', payload: { trackId: 'TRK-SD-010', headingDeg: 0, verticalRateFpm: 1500 } },
        { delay: 400, type: 'updateTrack', payload: { trackId: 'TRK-SD-007', headingDeg: 135 } },
      ],
    },
    {
      id: 'tornado-clear',
      narrative: 'All aircraft clear of severe weather. Resuming normal operations.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 6000,
      events: [{ delay: 300, type: 'removeAlert', payload: { id: 'ALT-TORNADO' } }],
    },

    // ==================== FINALE ====================
    {
      id: 'finale-1',
      narrative: 'ATCS Next Generation. When everything goes wrong, we are the last line of defense.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 6000,
    },
    {
      id: 'finale-2',
      narrative: 'AI threat detection. Real-time crisis resolution. The future of air traffic control.',
      spotlight: { type: 'component', id: 'predictions' },
      autoAdvance: 6000,
    },
    {
      id: 'finale-3',
      narrative: 'Demo complete. Click any aircraft to issue commands. ATCS-NG: Protecting lives, every second.',
      spotlight: { type: 'component', id: 'radar' },
      autoAdvance: 10000,
    },
  ],
};
